.TH "graph" 3 "Wed Feb 26 2020" "Version V2.0" "JerryScript interface documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph \- data_plot class interface  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jerryscript_h\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBadd\fP (double sizer_index_d, string name_str, double graph_range_d, double buffer_length_d, double time_step_d)"
.br
.RI "Add new graph\&. "
.ti -1c
.RI "double \fBinsert_signal\fP (double graph_index_d, string name_str, double color_d, double width_d, double style_d)"
.br
.RI "Insert graph signal\&. "
.ti -1c
.RI "bool \fBset\fP (double graph_index_d, vector< double > &v_data_d)"
.br
.RI "Set graph value\&. "
.in -1c
.SH "Detailed Description"
.PP 
data_plot class interface 
.PP
Definition at line 1464 of file jerryscript_h\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double add (double sizer_index_d, string name_str, double graph_range_d, double buffer_length_d, double time_step_d)"

.PP
Add new graph\&. 
.PP
.nf
var test_panel;
var test_sizer;
var test_graph;
test_panel = gui\&.panel\&.add("test_panel", true);
test_sizer = gui\&.panel\&.get_sizer(test_panel);
test_graph = gui\&.graph\&.add(test_sizer, "data", 3000\&.0, 40\&.0, 0\&.1);

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP sizer_index_d : Parent sizer index 
.br
\fI[IN]\fP name_str : Graph name 
.br
\fI[IN]\fP graph_range_d : Range symetrical around 0 
.br
\fI[IN]\fP buffer_length_d : Sample memory size 
.br
\fI[IN]\fP time_step_d : Sample time\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
double : graph buffer index 
.RE
.PP

.SS "double insert_signal (double graph_index_d, string name_str, double color_d, double width_d, double style_d)"

.PP
Insert graph signal\&. 
.PP
.nf
var test_panel;
var test_sizer;
var test_graph;
var graph_signal = [];
var insert_state_val;
test_panel = gui\&.panel\&.add("test_panel", true);
test_sizer = gui\&.panel\&.get_sizer(test_panel);
test_graph = gui\&.graph\&.add(test_sizer, "data", 3000\&.0, 40\&.0, 0\&.1);
insert_state_val = gui\&.graph\&.insert_signal(test_graph, "signal",0xff000000,1,0);
graph_signal\&.push(0);

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP graph_index_d : graph index 
.br
\fI[IN]\fP name_str : Signal name 
.br
\fI[IN]\fP color_d : Signal line color 
.br
\fI[IN]\fP width_d : Signal line width 
.br
\fI[IN]\fP style_d : Signal style width 
.PD 0

.IP "\(bu" 2
0 : Solid 
.IP "\(bu" 2
1 : Dot 
.IP "\(bu" 2
2 : Long dash 
.IP "\(bu" 2
3 : Short dash 
.IP "\(bu" 2
4 : Dot dash 
.PP
.RE
.PP
\fBReturns:\fP
.RS 4
double : Signal insert status 
.RE
.PP

.SS "bool set (double graph_index_d, vector< double > & v_data_d)"

.PP
Set graph value\&. 
.PP
.nf
var test_panel;
var test_sizer;
var test_graph;
var graph_signal = [];
test_panel = gui\&.panel\&.add("test_panel", true);
test_sizer = gui\&.panel\&.get_sizer(test_panel);
test_graph = gui\&.graph\&.add(test_sizer, "data", 10\&.0, 5\&.0, 1);
graph_signal\&.push(gui\&.graph\&.insert_signal(test_graph, "signal",0xff000000,1,0));
graph_signal[0] = 10;
gui\&.graph\&.set(test_graph, graph_signal);
graph_signal[0] = 4;
gui\&.graph\&.set(test_graph, graph_signal);
graph_signal[0] = -8;
gui\&.graph\&.set(test_graph, graph_signal);
graph_signal[0] = 0;
gui\&.graph\&.set(test_graph, graph_signal);

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP graph_index_d : graph index 
.br
\fI[IN]\fP v_data_d : Signal data array with one sample per signal 
.RE
.PP
\fBReturns:\fP
.RS 4
bool : Set status 
.PD 0

.IP "\(bu" 2
false : Fail 
.IP "\(bu" 2
true : Update 
.PP
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JerryScript interface documentation from the source code\&.
