.TH "gui" 3 "Sun Feb 16 2020" "Version V2.0" "JerryScript interface documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui \- Main JS GUI object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jerryscript_h\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpanel\fP \fBpanel\fP"
.br
.ti -1c
.RI "\fBsizer\fP \fBsizer\fP"
.br
.ti -1c
.RI "\fBbutton\fP \fBbutton\fP"
.br
.ti -1c
.RI "\fBcheck_box\fP \fBcheck_box\fP"
.br
.ti -1c
.RI "\fBtextctrl\fP \fBtextctrl\fP"
.br
.ti -1c
.RI "\fBstatic_text\fP \fBstatic_text\fP"
.br
.ti -1c
.RI "\fBslider\fP \fBslider\fP"
.br
.ti -1c
.RI "\fBgauge\fP \fBgauge\fP"
.br
.ti -1c
.RI "\fBgraph\fP \fBgraph\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main JS GUI object\&. 
.PP
Definition at line 1458 of file jerryscript_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JerryScript interface documentation from the source code\&.
