.TH "GUI_user_object" 3 "Mon Apr 20 2020" "Version V2.0" "JerryScript interface documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUI_user_object \- User GUI object\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBgraph\fP"
.br
.RI "data_plot class interface "
.in -1c
.SH "Detailed Description"
.PP 
User GUI object\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for JerryScript interface documentation from the source code\&.
