.TH "GUI_object" 3 "Mon Apr 20 2020" "Version V2.0" "JerryScript interface documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUI_object \- wxWidget GUI object  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBpanel\fP"
.br
.RI "wxAui panel class "
.ti -1c
.RI "class \fBsizer\fP"
.br
.RI "wxSizer class interface "
.ti -1c
.RI "class \fBbutton\fP"
.br
.RI "wxButton class interface "
.ti -1c
.RI "class \fBcheck_box\fP"
.br
.RI "wxCheckBox class interface "
.ti -1c
.RI "class \fBtextctrl\fP"
.br
.RI "wxTextCtrl class interface "
.ti -1c
.RI "class \fBstatic_text\fP"
.br
.RI "wxStaticText class interface "
.ti -1c
.RI "class \fBslider\fP"
.br
.RI "wxSlider class interface "
.ti -1c
.RI "class \fBgauge\fP"
.br
.RI "wxGauge class interface "
.ti -1c
.RI "class \fBled\fP"
.br
.RI "wxLed class interface "
.in -1c
.SH "Detailed Description"
.PP 
wxWidget GUI object 


.SH "Author"
.PP 
Generated automatically by Doxygen for JerryScript interface documentation from the source code\&.
