.TH "jerryscript_h.h" 3 "Mon Apr 20 2020" "Version V2.0" "JerryScript interface documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jerryscript_h.h \- JerryScript class documentation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBmain_frame\fP"
.br
.RI "System Main frame GUI control\&. "
.ti -1c
.RI "class \fBuart\fP"
.br
.RI "System UART port driver\&. "
.ti -1c
.RI "class \fBtime\fP"
.br
.RI "System time interface\&. "
.ti -1c
.RI "class \fBtimer\fP"
.br
.RI "Event timer\&. "
.ti -1c
.RI "class \fBfile\fP"
.br
.RI "System file read/write\&. "
.ti -1c
.RI "class \fBproject\fP"
.br
.RI "Script project file\&. "
.ti -1c
.RI "class \fBpanel\fP"
.br
.RI "wxAui panel class "
.ti -1c
.RI "class \fBsizer\fP"
.br
.RI "wxSizer class interface "
.ti -1c
.RI "class \fBbutton\fP"
.br
.RI "wxButton class interface "
.ti -1c
.RI "class \fBcheck_box\fP"
.br
.RI "wxCheckBox class interface "
.ti -1c
.RI "class \fBtextctrl\fP"
.br
.RI "wxTextCtrl class interface "
.ti -1c
.RI "class \fBstatic_text\fP"
.br
.RI "wxStaticText class interface "
.ti -1c
.RI "class \fBslider\fP"
.br
.RI "wxSlider class interface "
.ti -1c
.RI "class \fBgauge\fP"
.br
.RI "wxGauge class interface "
.ti -1c
.RI "class \fBled\fP"
.br
.RI "wxLed class interface "
.ti -1c
.RI "class \fBgraph\fP"
.br
.RI "data_plot class interface "
.ti -1c
.RI "class \fBgui\fP"
.br
.RI "Main JS GUI object\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdelay\fP (time_d)"
.br
.RI "Delay\&. "
.ti -1c
.RI "\fBrand\fP ()"
.br
.RI "Get random value\&. "
.ti -1c
.RI "\fBrand\fP (min_d, max_d)"
.br
.RI "Get random value from range\&. "
.ti -1c
.RI "\fBalert\fP (text_str)"
.br
.RI "Show alert dialog\&. "
.ti -1c
.RI "\fBgui\fP (show_main_b)"
.br
.RI "Set show main frame\&. "
.ti -1c
.RI "\fBgui\fP (show_main_b, text_str)"
.br
.RI "Set show main frame and Script frame name\&. "
.ti -1c
.RI "\fBgui\fP (show_main_b, text_str, show_script_b)"
.br
.RI "Set show main frame and Script frame name\&. "
.ti -1c
.RI "\fBreg_exit\fP (function_str)"
.br
.RI "Register exit callback\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmain_frame\fP \fBmain_frame\fP"
.br
.ti -1c
.RI "\fBuart\fP \fBuart\fP"
.br
.ti -1c
.RI "\fBtime\fP \fBtime\fP"
.br
.ti -1c
.RI "\fBtimer\fP \fBtimer\fP"
.br
.ti -1c
.RI "\fBfile\fP \fBfile\fP"
.br
.ti -1c
.RI "\fBproject\fP \fBproject\fP"
.br
.ti -1c
.RI "\fBgui\fP \fBgui\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
JerryScript class documentation\&. 


.PP
\fBAuthor:\fP
.RS 4
Ing\&. Petr Simek 
.RE
.PP
\fBVersion:\fP
.RS 4
V1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
05\&.12\&.2019 
.RE
.PP
\fBAttention:\fP
.RS 4
.SS "(C) COPYRIGHT PORTTRONIC"
.RE
.PP

.PP
Definition in file \fBjerryscript_h\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JerryScript interface documentation from the source code\&.
