.TH "panel" 3 "Wed Feb 26 2020" "Version V2.0" "JerryScript interface documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel \- wxAui panel class  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jerryscript_h\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBadd\fP (string name_str, bool horizontal_b)"
.br
.RI "Add new AUI panel\&. "
.ti -1c
.RI "double \fBget_sizer\fP (double panel_d)"
.br
.RI "Get panel main sizer\&. "
.in -1c
.SH "Detailed Description"
.PP 
wxAui panel class 
.PP
Definition at line 854 of file jerryscript_h\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double add (string name_str, bool horizontal_b)"

.PP
Add new AUI panel\&. 
.PP
.nf
var test_panel;
test_panel = gui\&.panel\&.add("test_panel", true);

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP name_str : Panel name 
.br
\fI[IN]\fP horizontal_b : Basic sizer orientation 
.PD 0

.IP "\(bu" 2
false : Vertical 
.IP "\(bu" 2
true : Horizontal 
.PP
.RE
.PP
\fBReturns:\fP
.RS 4
double : Panel buffer index 
.RE
.PP

.SS "double get_sizer (double panel_d)"

.PP
Get panel main sizer\&. 
.PP
.nf
var test_panel;
var test_sizer;
test_panel = gui\&.panel\&.add("test_panel", true);
test_sizer = gui\&.panel\&.get_sizer(test_panel);

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP panel_d : Panel buffer index 
.RE
.PP
\fBReturns:\fP
.RS 4
double : Sizer buffer index 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JerryScript interface documentation from the source code\&.
