.TH "Public_variable" 3 "Mon Apr 20 2020" "Version V2.0" "JerryScript interface documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Public_variable \- Global public variable\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmain_frame\fP \fBmain_frame\fP"
.br
.ti -1c
.RI "\fBuart\fP \fBuart\fP"
.br
.ti -1c
.RI "\fBtime\fP \fBtime\fP"
.br
.ti -1c
.RI "\fBtimer\fP \fBtimer\fP"
.br
.ti -1c
.RI "\fBfile\fP \fBfile\fP"
.br
.ti -1c
.RI "\fBproject\fP \fBproject\fP"
.br
.ti -1c
.RI "\fBgui\fP \fBgui\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Global public variable\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for JerryScript interface documentation from the source code\&.
