.TH "sizer" 3 "Mon Apr 20 2020" "Version V2.0" "JerryScript interface documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sizer \- wxSizer class interface  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jerryscript_h\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBadd\fP (sizer_index_d, proportion_d, horizontal_b)"
.br
.RI "Add new AUI panel\&. "
.in -1c
.SH "Detailed Description"
.PP 
wxSizer class interface 
.PP
Definition at line 940 of file jerryscript_h\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "add (sizer_index_d, proportion_d, horizontal_b)"

.PP
Add new AUI panel\&. 
.PP
.nf
var test_panel;
var test_sizer;
var item_sizer;
test_panel = gui\&.panel\&.add("test_panel", true);
test_sizer = gui\&.panel\&.get_sizer(test_panel);
item_sizer = gui\&.sizer\&.add(test_sizer, 0, true);

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP sizer_index_d : Parent sizer index 
.br
\fI[IN]\fP proportion_d : Proportion in parent sizer element 
.br
\fI[IN]\fP horizontal_b : Sizer orientation 
.PD 0

.IP "\(bu" 2
false : Vertical 
.IP "\(bu" 2
true : Horizontal 
.PP
.RE
.PP
\fBReturns:\fP
.RS 4
Sizer index 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JerryScript interface documentation from the source code\&.
