.TH "System_object" 3 "Sun Feb 16 2020" "Version V2.0" "JerryScript interface documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System_object \- Basic system object\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBmain_frame\fP"
.br
.RI "System Main frame GUI control\&. "
.ti -1c
.RI "class \fBuart\fP"
.br
.RI "System UART port driver\&. "
.ti -1c
.RI "class \fBtime\fP"
.br
.RI "System time interface\&. "
.ti -1c
.RI "class \fBfile\fP"
.br
.RI "System file read/write\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdelay\fP (double time_d)"
.br
.RI "Delay\&. "
.ti -1c
.RI "void \fBalert\fP (string text_str)"
.br
.RI "Show alert dialog\&. "
.ti -1c
.RI "void \fBgui\fP (bool enable_b)"
.br
.RI "Set show main frame\&. "
.ti -1c
.RI "void \fBgui\fP (bool enable_b, string text_str)"
.br
.RI "Set show main frame and Script frame name\&. "
.ti -1c
.RI "void \fBgui\fP (bool enable_b, string text_str, bool enable_b)"
.br
.RI "Set show main frame and Script frame name\&. "
.in -1c
.SH "Detailed Description"
.PP 
Basic system object\&. 


.SH "Function Documentation"
.PP 
.SS "void alert (string text_str)"

.PP
Show alert dialog\&. 
.PP
.nf
alert("Hello world!");

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP text_str : Alert text 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void delay (double time_d)"

.PP
Delay\&. 
.PP
.nf
// Delay 1s
delay(1000);

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP time_d : Delay time in ms 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void \fBgui\fP (bool enable_b)"

.PP
Set show main frame\&. 
.PP
.nf
gui(false);

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP enable_b : Show main frame 
.PD 0

.IP "\(bu" 2
false : Hide 
.IP "\(bu" 2
true : Show 
.PP
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void \fBgui\fP (bool enable_b, string text_str)"

.PP
Set show main frame and Script frame name\&. 
.PP
.nf
gui(false, "Script frame");

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP enable_b : Show main frame 
.PD 0

.IP "\(bu" 2
false : Hide 
.IP "\(bu" 2
true : Show 
.PP
.br
\fI[IN]\fP text_str : Script frame name 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void \fBgui\fP (bool enable_b, string text_str, bool enable_b)"

.PP
Set show main frame and Script frame name\&. 
.PP
.nf
gui(false, "Script frame", true);

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP enable_b : Show main frame 
.PD 0

.IP "\(bu" 2
false : Hide 
.IP "\(bu" 2
true : Show 
.PP
.br
\fI[IN]\fP text_str : Script frame name 
.br
\fI[IN]\fP enable_b : Show script frame 
.PD 0

.IP "\(bu" 2
false : Hide 
.IP "\(bu" 2
true : Show 
.PP
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for JerryScript interface documentation from the source code\&.
