.TH "System_object" 3 "Mon Apr 20 2020" "Version V2.0" "JerryScript interface documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System_object \- Basic system object\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBmain_frame\fP"
.br
.RI "System Main frame GUI control\&. "
.ti -1c
.RI "class \fBuart\fP"
.br
.RI "System UART port driver\&. "
.ti -1c
.RI "class \fBtime\fP"
.br
.RI "System time interface\&. "
.ti -1c
.RI "class \fBtimer\fP"
.br
.RI "Event timer\&. "
.ti -1c
.RI "class \fBfile\fP"
.br
.RI "System file read/write\&. "
.ti -1c
.RI "class \fBproject\fP"
.br
.RI "Script project file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Basic system object\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for JerryScript interface documentation from the source code\&.
