.TH "textctrl" 3 "Sun Feb 16 2020" "Version V2.0" "JerryScript interface documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textctrl \- wxTextCtrl class interface  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jerryscript_h\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBadd\fP (double sizer_index_d, wxString text_str, double proportion_d, bool expand_b, bool multiline_b)"
.br
.RI "Add new text control\&. "
.ti -1c
.RI "string \fBget\fP (double textctrl_index_d, double line_d)"
.br
.RI "Get text control string\&. "
.ti -1c
.RI "bool \fBset\fP (double textctrl_index_d, string text_str)"
.br
.RI "Set text control string\&. "
.ti -1c
.RI "bool \fBappend\fP (double textctrl_index_d, string text_str)"
.br
.RI "Append text control string\&. "
.in -1c
.SH "Detailed Description"
.PP 
wxTextCtrl class interface 
.PP
Definition at line 1002 of file jerryscript_h\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double add (double sizer_index_d, wxString text_str, double proportion_d, bool expand_b, bool multiline_b)"

.PP
Add new text control\&. 
.PP
.nf
var test_panel;
var test_sizer;
var test_textctrl;
test_panel = gui\&.panel\&.add("test_panel", true);
test_sizer = gui\&.panel\&.get_sizer(test_panel);
test_textctrl = gui\&.textctrl\&.add(test_sizer, "Hello world!", 0, false, true);

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP sizer_index_d : Parent sizer index 
.br
\fI[IN]\fP text_str : Default text 
.br
\fI[IN]\fP proportion_d : Proportion in parent sizer element 
.br
\fI[IN]\fP expand_b : Expand in sizer flag 
.PD 0

.IP "\(bu" 2
false : Default size 
.IP "\(bu" 2
true : Expand 
.PP
.br
\fI[IN]\fP multiline_b : Multiline enable 
.PD 0

.IP "\(bu" 2
false : One line 
.IP "\(bu" 2
true : Multiline 
.PP
.RE
.PP
\fBReturns:\fP
.RS 4
double : textctrl buffer index 
.RE
.PP

.SS "bool append (double textctrl_index_d, string text_str)"

.PP
Append text control string\&. 
.PP
.nf
var test_panel;
var test_sizer;
var test_textctrl;
var test_status_bool;
test_panel = gui\&.panel\&.add("test_panel", true);
test_sizer = gui\&.panel\&.get_sizer(test_panel);
test_textctrl = gui\&.textctrl\&.add(test_sizer, "", 0, false, true);
test_status_bool = gui\&.textctrl\&.append(test_textctrl, "Hello world!");

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP textctrl_index_d : Text control index 
.br
\fI[IN]\fP text_str : New text (Append text at the end) 
.RE
.PP
\fBReturns:\fP
.RS 4
bool : Append status 
.PD 0

.IP "\(bu" 2
false : Fail 
.IP "\(bu" 2
true : Changed 
.PP
.RE
.PP

.SS "string get (double textctrl_index_d, double line_d)"

.PP
Get text control string\&. 
.PP
.nf
var test_panel;
var test_sizer;
var test_textctrl;
var text_str;
test_panel = gui\&.panel\&.add("test_panel", true);
test_sizer = gui\&.panel\&.get_sizer(test_panel);
test_textctrl = gui\&.textctrl\&.add(test_sizer, "", 0, false, true);
text_str = gui\&.textctrl\&.get(test_textctrl, 0);

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP textctrl_index_d : Text control index 
.br
\fI[IN]\fP line_d : Read line number 
.RE
.PP
\fBReturns:\fP
.RS 4
string : Read data 
.RE
.PP

.SS "bool set (double textctrl_index_d, string text_str)"

.PP
Set text control string\&. 
.PP
.nf
var test_panel;
var test_sizer;
var test_textctrl;
var test_status_bool;
test_panel = gui\&.panel\&.add("test_panel", true);
test_sizer = gui\&.panel\&.get_sizer(test_panel);
test_textctrl = gui\&.textctrl\&.add(test_sizer, "", 0, false, true);
test_status_bool = gui\&.textctrl\&.set(test_textctrl, "Hello world!");

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP textctrl_index_d : Text control index 
.br
\fI[IN]\fP text_str : New text (Erase textctrl before set) 
.RE
.PP
\fBReturns:\fP
.RS 4
bool : Change status 
.PD 0

.IP "\(bu" 2
false : Fail 
.IP "\(bu" 2
true : Changed 
.PP
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JerryScript interface documentation from the source code\&.
