.TH "time" 3 "Sun Feb 16 2020" "Version V2.0" "JerryScript interface documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
time \- System time interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jerryscript_h\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBnow\fP (void)"
.br
.RI "Get actual time in s\&. "
.ti -1c
.RI "double \fBnow_ms\fP (void)"
.br
.RI "Get actual time in ms\&. "
.ti -1c
.RI "string \fBstr\fP (void)"
.br
.RI "Get actual UTC time string\&. "
.ti -1c
.RI "string \fBlocal_str\fP (void)"
.br
.RI "Get actual local time string\&. "
.in -1c
.SH "Detailed Description"
.PP 
System time interface\&. 
.PP
Definition at line 545 of file jerryscript_h\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "string local_str (void)"

.PP
Get actual local time string\&. 
.PP
.nf
var time_str;
time_str = time\&.local_str();

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string : Time and date (YYYY-MM-DD HH:MM:SS) 
.RE
.PP

.SS "double now (void)"

.PP
Get actual time in s\&. 
.PP
.nf
var time_var;
time_var = time\&.now();

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
double : Number of s from (ISO 8601: 1970-01-01T00:00:00Z) 
.RE
.PP

.SS "double now_ms (void)"

.PP
Get actual time in ms\&. 
.PP
.nf
var time_var;
time_var = time\&.now_ms();

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
double : Number of ms from (ISO 8601: 1970-01-01T00:00:00Z) 
.RE
.PP

.SS "string str (void)"

.PP
Get actual UTC time string\&. 
.PP
.nf
var time_str;
time_str = time\&.str();

.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string : Time and date (YYYY-MM-DD HH:MM:SS) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JerryScript interface documentation from the source code\&.
