.TH "D:/project/uart_terminal/application/editor/ap_editor_frame_cpp.cpp" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/project/uart_terminal/application/editor/ap_editor_frame_cpp.cpp \- Text editor window component creator\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ap_editor_frame_h\&.h'\fP
.br
\fC#include 'ap_uart_terminal_frame_h\&.h'\fP
.br
\fC#include <wx/bitmap\&.h>\fP
.br
\fC#include <wx/image\&.h>\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include <wx/string\&.h>\fP
.br
\fC#include <wx/msgdlg\&.h>\fP
.br
\fC#include 'lp_editor_xpm\&.xpm'\fP
.br
\fC#include 'lp_new_xpm\&.xpm'\fP
.br
\fC#include 'lp_new_template_xpm\&.xpm'\fP
.br
\fC#include 'lp_open_xpm\&.xpm'\fP
.br
\fC#include 'lp_save_xpm\&.xpm'\fP
.br
\fC#include 'lp_saveas_xpm\&.xpm'\fP
.br
\fC#include 'lp_find_xpm\&.xpm'\fP
.br
\fC#include 'lp_find_next_xpm\&.xpm'\fP
.br
\fC#include 'lp_find_prev_xpm\&.xpm'\fP
.br
\fC#include 'lp_replace_xpm\&.xpm'\fP
.br
\fC#include 'lp_goto_xpm\&.xpm'\fP
.br
\fC#include 'lp_quit_xpm\&.xpm'\fP
.br
\fC#include 'lp_info_xpm\&.xpm'\fP
.br
\fC#include 'lp_js_xpm\&.xpm'\fP
.br

.SH "Detailed Description"
.PP 
Text editor window component creator\&. 


.PP
\fBAuthor:\fP
.RS 4
Ing\&. Petr Simek 
.RE
.PP
\fBVersion:\fP
.RS 4
V1\&.5 
.RE
.PP
\fBDate:\fP
.RS 4
28\&.03\&.2020 
.RE
.PP
\fBAttention:\fP
.RS 4
.SS "(C) COPYRIGHT PORTTRONIC"
.RE
.PP

.PP
Definition in file \fBap_editor_frame_cpp\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
