.TH "D:/project/uart_terminal/application/uart_terminal/ap_uart_terminal_frame_cpp.cpp" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/project/uart_terminal/application/uart_terminal/ap_uart_terminal_frame_cpp.cpp \- Application window component creator\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ap_uart_terminal_frame_h\&.h'\fP
.br
\fC#include <wx/msgdlg\&.h>\fP
.br
\fC#include <wx/file\&.h>\fP
.br
\fC#include <wx/font\&.h>\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include <wx/string\&.h>\fP
.br
\fC#include <wx/imaglist\&.h>\fP
.br
\fC#include <wx/filename\&.h>\fP
.br
\fC#include 'icon/ap_ut_icon_app_xpm\&.xpm'\fP
.br
\fC#include 'icon/lp_play_ico_xpm\&.xpm'\fP
.br
\fC#include 'icon/lp_stop_ico_xpm\&.xpm'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBd_ap_uart_terminal_tx_buffer_length\fP   4096"
.br
.ti -1c
.RI "#define \fBd_ap_uart_terminal_status_port\fP   0"
.br
.ti -1c
.RI "#define \fBd_ap_uart_terminal_status_script\fP   1"
.br
.ti -1c
.RI "#define \fBd_ap_uart_terminal_info_script\fP   2"
.br
.in -1c
.SH "Detailed Description"
.PP 
Application window component creator\&. 


.PP
\fBAuthor:\fP
.RS 4
Ing\&. Petr Simek 
.RE
.PP
\fBVersion:\fP
.RS 4
V1\&.5 
.RE
.PP
\fBDate:\fP
.RS 4
04\&.03\&.2014 
.RE
.PP
\fBAttention:\fP
.RS 4
.SS "(C) COPYRIGHT PORTTRONIC"
.RE
.PP

.PP
Definition in file \fBap_uart_terminal_frame_cpp\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
