.TH "D:/project/uart_terminal/application/uart_terminal/ap_uart_terminal_frame_h.h" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/project/uart_terminal/application/uart_terminal/ap_uart_terminal_frame_h.h \- Application window component creator\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <wx/button\&.h>\fP
.br
\fC#include <wx/checkbox\&.h>\fP
.br
\fC#include <wx/choice\&.h>\fP
.br
\fC#include <wx/filedlg\&.h>\fP
.br
\fC#include <wx/frame\&.h>\fP
.br
\fC#include <wx/led\&.h>\fP
.br
\fC#include <wx/menu\&.h>\fP
.br
\fC#include <wx/panel\&.h>\fP
.br
\fC#include <wx/sizer\&.h>\fP
.br
\fC#include <wx/stattext\&.h>\fP
.br
\fC#include <wx/statusbr\&.h>\fP
.br
\fC#include <wx/textctrl\&.h>\fP
.br
\fC#include <wx/tglbtn\&.h>\fP
.br
\fC#include <wx/timer\&.h>\fP
.br
\fC#include <wx/textdlg\&.h>\fP
.br
\fC#include <wx/progdlg\&.h>\fP
.br
\fC#include 'hw_dr_uart_driver_h\&.h'\fP
.br
\fC#include 'in_config_ini_wrapper_h\&.h'\fP
.br
\fC#include 'in_jerryscript_port_h\&.h'\fP
.br
\fC#include 'ap_editor_frame_h\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBmain_frame\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBsend_event_fct\fP) (void *p_parametr_void, uint8_t *p_data_sui8, uint32_t length_ui32)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Application window component creator\&. 


.PP
\fBAuthor:\fP
.RS 4
Ing\&. Petr Simek 
.RE
.PP
\fBVersion:\fP
.RS 4
V1\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
04\&.03\&.2014 
.RE
.PP
\fBAttention:\fP
.RS 4
.SS "(C) COPYRIGHT PORTTRONIC"
.RE
.PP

.PP
Definition in file \fBap_uart_terminal_frame_h\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
