.TH "autocomp_buffer_t" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autocomp_buffer_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <in_js_edit_text_h\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "wxString \fBclass_str\fP"
.br
.ti -1c
.RI "wxString \fBmethod_str\fP"
.br
.ti -1c
.RI "wxString \fBdoc_str\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct 
.PP
Definition at line 51 of file in_js_edit_text_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
