.TH "config_ini" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_ini
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <in_config_ini_wrapper_h\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconfig_ini\fP (wxString path_str)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~config_ini\fP (void)"
.br
.RI "Destructor\&. "
.ti -1c
.RI "int32_t \fBget_value\fP (wxString path_str, wxString default_value_str)"
.br
.RI "Read value from INI\&. "
.ti -1c
.RI "wxString \fBget_string\fP (wxString path_str, wxString default_value_str)"
.br
.RI "Read string value from INI\&. "
.ti -1c
.RI "void \fBset_value\fP (wxString path_str, int32_t value_i32)"
.br
.RI "Set value in to INI\&. "
.ti -1c
.RI "void \fBset_string\fP (wxString path_str, wxString value_str)"
.br
.RI "Set string value in to INI\&. "
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "wxString \fBerror_text_str\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class 
.PP
Definition at line 41 of file in_config_ini_wrapper_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
