.TH "console_buffer_t" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
console_buffer_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "wxString \fBtext_str\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct 
.PP
Definition at line 63 of file ap_uart_terminal_frame_cpp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
