.TH "data_plot" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_plot
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <in_data_plot_graph_h\&.h>\fP
.PP
Inherits wxPanel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdata_plot\fP (wxWindow *p_parent_wxwindow, wxString name_str, double min_d, double max_d, double length_d, double step_d)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~data_plot\fP (void)"
.br
.RI "Destructor\&. "
.ti -1c
.RI "void \fBadd\fP (wxString signal_label_str, wxPen signal_style_pen)"
.br
.RI "Add new plot signal\&. "
.ti -1c
.RI "void \fBerase\fP (wxString signal_label_str)"
.br
.RI "Delete signal from math plot\&. "
.ti -1c
.RI "uint32_t \fBget\fP (void)"
.br
.RI "Return number of signal buffer in graph\&. "
.ti -1c
.RI "bool \fBset\fP (wxString signal_label_str, double data_d)"
.br
.RI "Set signal data by name\&. "
.ti -1c
.RI "bool \fBset\fP (uint32_t signal_ui32, double data_d)"
.br
.RI "Set signal data by index\&. "
.ti -1c
.RI "void \fBshow\fP (wxString signal_label_str, bool show_b)"
.br
.RI "Set signal visibility\&. "
.ti -1c
.RI "bool \fBset_time\fP (double length_d, double step_d)"
.br
.RI "Set logged data length and sample period\&. "
.ti -1c
.RI "void \fBset_range\fP (double max_d, double min_d)"
.br
.RI "Set graph range\&. "
.ti -1c
.RI "void \fBredraw\fP (void)"
.br
.RI "Redraw new data and set time cursor\&. "
.ti -1c
.RI "void \fBfit\fP (bool default_b=true)"
.br
.RI "Set graph in to default zoom\&. "
.ti -1c
.RI "void \fBpause\fP (bool pause_b)"
.br
.RI "Redraw data pause\&. "
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const long \fBl_id_name_wxstatictext\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBl_id_pause_wxtogglebutton\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBl_id_zoom_wxbutton\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBl_id_zoom_plus_wxbutton\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBl_id_zoom_minus_wxbutton\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBl_id_legend_wxcheckbox\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBl_id_x_axis_mpscalex\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBl_id_y_axis_mpscalex\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBl_id_graph_mpwindow\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBl_id_graph_signal_wxgrid\fP = wxNewId()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class 
.PP
Definition at line 69 of file in_data_plot_graph_h\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const long l_id_name_wxstatictext = wxNewId()\fC [static]\fP, \fC [protected]\fP"
Library
.PP
Local variable 
.PP
Definition at line 90 of file in_data_plot_graph_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
