.TH "Debuger" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Debuger
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBjerryx_debugger_after_connect\fP (bool success)"
.br
.ti -1c
.RI "bool \fBjerryx_debugger_tcp_create\fP (uint16_t port)"
.br
.ti -1c
.RI "bool \fBjerryx_debugger_ws_create\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void jerryx_debugger_after_connect (bool success)"
Function 
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
