.TH "Driver" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Driver \- Device driver\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUART\fP"
.br
.RI "UART class definition\&. "
.in -1c
.SH "Detailed Description"
.PP 
Device driver\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
