.TH "Edit_text_gen" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Edit_text_gen \- JavaScript text editor generated autocompetation\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
JavaScript text editor generated autocompetation\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
