.TH "editor_frame" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
editor_frame
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ap_editor_frame_h\&.h>\fP
.PP
Inherits wxFrame\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBe_path\fP = 0, \fBe_position\fP = 1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeditor_frame\fP (wxWindow *p_parent_window)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~editor_frame\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "void \fBload\fP (wxString path_str)"
.br
.RI "Load file\&. "
.ti -1c
.RI "void \fBrun\fP (bool status_b)"
.br
.RI "Set editor run button state\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class 
.PP
Definition at line 48 of file ap_editor_frame_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
