.TH "event_buffer_t" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
event_buffer_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "wxString \fBevent_str\fP"
.br
.ti -1c
.RI "uint32_t \fBcomponent_id_ui32\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct 
.PP
Definition at line 53 of file in_jerryscript_port_cpp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
