.TH "file_js_c" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_js_c
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <in_js_class_file_js_h\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreg_host_class\fP (void)"
.br
.RI "Registration object in to class\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static uint32_t \fBread\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Read file (JS function 'read') "
.ti -1c
.RI "static uint32_t \fBread_b\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Read file (JS function 'read_b') "
.ti -1c
.RI "static uint32_t \fBwrite\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Read file (JS function 'write') "
.ti -1c
.RI "static uint32_t \fBappend\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Read file (JS function 'append') "
.in -1c
.SH "Detailed Description"
.PP 
Class 
.PP
Definition at line 51 of file in_js_class_file_js_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
