.TH "GUI" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUI \- GUI window\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBButton\fP"
.br
.RI "Button class definition\&. "
.ti -1c
.RI "\fBCheck_box\fP"
.br
.RI "Check box class definition\&. "
.ti -1c
.RI "\fBGauge\fP"
.br
.RI "Gauge class definition\&. "
.ti -1c
.RI "\fBGraph\fP"
.br
.RI "Graph interface\&. "
.ti -1c
.RI "\fBPanel\fP"
.br
.RI "Panel class definition\&. "
.ti -1c
.RI "\fBSizer\fP"
.br
.RI "Sizer class definition\&. "
.ti -1c
.RI "\fBSlider\fP"
.br
.RI "Slider class definition\&. "
.ti -1c
.RI "\fBStatic_text\fP"
.br
.RI "Static text class definition\&. "
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBgui_frame\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgui_frame\fP (wxWindow *p_parent_window, void *p_jerryscript_void)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~gui_frame\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "wxAuiManager * \fBget_aui_manager\fP (void)"
.br
.RI "Get AUI manager\&. "
.ti -1c
.RI "void \fBframe_show\fP (bool status_b, wxString name_str)"
.br
.RI "Show frame\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBl_frmae_show_b\fP = false"
.br
.ti -1c
.RI "bool \fBl_frame_show_bkp_b\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
GUI window\&. 


.SH "Function Documentation"
.PP 
.SS "void frame_show (bool status_b, wxString name_str)"

.PP
Show frame\&. 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP status_b : Show status 
.br
\fI[IN]\fP name_str : Frame label text 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 168 of file in_js_gui_frame_cpp\&.cpp\&.
.SS "wxAuiManager * get_aui_manager (void)"

.PP
Get AUI manager\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
wxAuiManager : AUI object pointer 
.RE
.PP

.PP
Definition at line 155 of file in_js_gui_frame_cpp\&.cpp\&.
.SS "\fBgui_frame\fP (wxWindow * parent, void * p_jerryscript_void)"

.PP
Constructor\&. Function
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP parent : Pointer on window generated by OS for application 
.br
\fI[IN]\fP id : Window identification 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 83 of file in_js_gui_frame_cpp\&.cpp\&.
.SS "~\fBgui_frame\fP ()\fC [virtual]\fP"

.PP
Destructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 125 of file in_js_gui_frame_cpp\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "bool l_frmae_show_b = false"
Define
.PP
Local variable 
.PP
Definition at line 55 of file in_js_gui_frame_cpp\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
