.TH "D:/project/uart_terminal/infrastructure/data_plot/in_data_plot_graph_h.h" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/project/uart_terminal/infrastructure/data_plot/in_data_plot_graph_h.h \- Interpret real-time data\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <mathplot\&.h>\fP
.br
\fC#include <wx/grid\&.h>\fP
.br
\fC#include <wx/panel\&.h>\fP
.br
\fC#include <wx/sizer\&.h>\fP
.br
\fC#include <wx/stattext\&.h>\fP
.br
\fC#include <wx/timer\&.h>\fP
.br
\fC#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBdata_plot_buffer\fP"
.br
.ti -1c
.RI "class \fBdata_plot\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interpret real-time data\&. 


.PP
\fBAuthor:\fP
.RS 4
Ing\&. Petr Simek 
.RE
.PP
\fBVersion:\fP
.RS 4
V1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
11\&.05\&.2015 
.RE
.PP
\fBAttention:\fP
.RS 4
.SS "(C) COPYRIGHT PORTTRONIC"
.RE
.PP

.PP
Definition in file \fBin_data_plot_graph_h\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
