.TH "D:/project/uart_terminal/infrastructure/jerryscript/gui/in_js_gui_button_cpp.cpp" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/project/uart_terminal/infrastructure/jerryscript/gui/in_js_gui_button_cpp.cpp \- GUI window button component\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'in_js_gui_frame_h\&.h'\fP
.br
\fC#include 'in_jerryscript_port_h\&.h'\fP
.br
\fC#include <wx/button\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBbutton_buffer_t\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "vector< \fBbutton_buffer_t\fP > \fBlv_data_button_buffer\fP"
.br
.ti -1c
.RI "uint32_t \fBl_cnt_button_ui32\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
GUI window button component\&. 


.PP
\fBAuthor:\fP
.RS 4
Ing\&. Petr Simek 
.RE
.PP
\fBVersion:\fP
.RS 4
V1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
10\&.09\&.2018 
.RE
.PP
\fBAttention:\fP
.RS 4
.SS "(C) COPYRIGHT PORTTRONIC"
.RE
.PP

.PP
Definition in file \fBin_js_gui_button_cpp\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
