.TH "D:/project/uart_terminal/infrastructure/jerryscript/in_jerryscript_editor_cpp.cpp" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/project/uart_terminal/infrastructure/jerryscript/in_jerryscript_editor_cpp.cpp \- JerryScript file editor panel\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'in_jerryscript_editor_h\&.h'\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include <wx/string\&.h>\fP
.br
\fC#include <wx/msgdlg\&.h>\fP
.br
\fC#include <wx/icon\&.h>\fP
.br
\fC#include <wx/filename\&.h>\fP
.br
\fC#include <Lmcons\&.h>\fP
.br
\fC#include 'lp_play_xpm\&.xpm'\fP
.br
\fC#include 'lp_stop_xpm\&.xpm'\fP
.br
\fC#include 'lp_open_xpm\&.xpm'\fP
.br
\fC#include 'lp_save_xpm\&.xpm'\fP
.br
\fC#include 'lp_saveas_xpm\&.xpm'\fP
.br
\fC#include 'lp_find_xpm\&.xpm'\fP
.br
\fC#include 'lp_replace_xpm\&.xpm'\fP
.br
\fC#include 'lp_new_xpm\&.xpm'\fP
.br
\fC#include 'lp_new_template_xpm\&.xpm'\fP
.br

.SH "Detailed Description"
.PP 
JerryScript file editor panel\&. 


.PP
\fBAuthor:\fP
.RS 4
Ing\&. Petr Simek 
.RE
.PP
\fBVersion:\fP
.RS 4
V1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
28\&.03\&.2020 
.RE
.PP
\fBAttention:\fP
.RS 4
.SS "(C) COPYRIGHT PORTTRONIC"
.RE
.PP

.PP
Definition in file \fBin_jerryscript_editor_cpp\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
