.TH "D:/project/uart_terminal/infrastructure/jerryscript/edit/in_js_edit_text_doc_h.h" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/project/uart_terminal/infrastructure/jerryscript/edit/in_js_edit_text_doc_h.h \- File variable wxString l_js_doc_file_str\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "wxString \fBl_js_doc_file_str\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
File variable wxString l_js_doc_file_str\&. 


.PP
\fBAuthor:\fP
.RS 4
file2str 
.RE
.PP

.PP
Definition in file \fBin_js_edit_text_doc_h\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "wxString l_js_doc_file_str"
Variable 
.PP
Definition at line 16 of file in_js_edit_text_doc_h\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
