.TH "D:/project/uart_terminal/infrastructure/jerryscript/gui/in_js_gui_frame_h.h" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/project/uart_terminal/infrastructure/jerryscript/gui/in_js_gui_frame_h.h \- GUI window component creator\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <wx/aui/aui\&.h>\fP
.br
\fC#include <wx/frame\&.h>\fP
.br
\fC#include <wx/timer\&.h>\fP
.br
\fC#include <wx/panel\&.h>\fP
.br
\fC#include <wx/sizer\&.h>\fP
.br
\fC#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBgui_frame\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
GUI window component creator\&. 


.PP
\fBAuthor:\fP
.RS 4
Ing\&. Petr Simek 
.RE
.PP
\fBVersion:\fP
.RS 4
V1\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
17\&.07\&.2018 
.RE
.PP
\fBAttention:\fP
.RS 4
.SS "(C) COPYRIGHT PORTTRONIC"
.RE
.PP

.PP
Definition in file \fBin_js_gui_frame_h\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
