.TH "D:/project/uart_terminal/infrastructure/jerryscript/in_jerryscript_debugger_h.h" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/project/uart_terminal/infrastructure/jerryscript/in_jerryscript_debugger_h.h \- JavaScript interpreter core function\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'in_jerryscript_core_h\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBjerryx_debugger_after_connect\fP (bool success)"
.br
.ti -1c
.RI "bool \fBjerryx_debugger_tcp_create\fP (uint16_t port)"
.br
.ti -1c
.RI "bool \fBjerryx_debugger_ws_create\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
JavaScript interpreter core function\&. 


.PP
\fBAuthor:\fP
.RS 4
js\&.foundation 
.RE
.PP
\fBVersion:\fP
.RS 4
V1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
22\&.04\&.2018 
.RE
.PP
\fBAttention:\fP
.RS 4
.SS " (C) JS Foundation and other contributors, http://js.foundation "
.RE
.PP
Licensed under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at 
.PP
.nf
http://www.apache.org/licenses/LICENSE-2.0

.fi
.PP
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&. 
.PP
Definition in file \fBin_jerryscript_debugger_h\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
