.TH "D:/project/uart_terminal/infrastructure/jerryscript/class/in_js_class_gauge_js_cpp.cpp" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/project/uart_terminal/infrastructure/jerryscript/class/in_js_class_gauge_js_cpp.cpp \- JerryScript wrapper for component gauge\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <wx/utils\&.h>\fP
.br
\fC#include 'in_js_class_gauge_js_h\&.h'\fP
.br
\fC#include 'in_jerryscript_core_h\&.h'\fP
.br
\fC#include 'in_js_gui_frame_h\&.h'\fP
.br

.SH "Detailed Description"
.PP 
JerryScript wrapper for component gauge\&. 


.PP
\fBAuthor:\fP
.RS 4
Ing\&. Petr Simek 
.RE
.PP
\fBVersion:\fP
.RS 4
V1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
30\&.10\&.2018 
.RE
.PP
\fBAttention:\fP
.RS 4
.SS "(C) COPYRIGHT PORTTRONIC"
.RE
.PP

.PP
Definition in file \fBin_js_class_gauge_js_cpp\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
