.TH "D:/project/uart_terminal/infrastructure/jerryscript/edit/in_js_edit_text_cpp.cpp" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/project/uart_terminal/infrastructure/jerryscript/edit/in_js_edit_text_cpp.cpp \- JerryScript text editor base on wxScintilla\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'in_js_edit_text_h\&.h'\fP
.br
\fC#include 'lp_class_public_xpm\&.xpm'\fP
.br
\fC#include 'lp_method_public_xpm\&.xpm'\fP
.br
\fC#include 'lp_var_public_xpm\&.xpm'\fP
.br
\fC#include 'in_js_edit_text_doc_h\&.h'\fP
.br

.SH "Detailed Description"
.PP 
JerryScript text editor base on wxScintilla\&. 


.PP
\fBAuthor:\fP
.RS 4
Ing\&. Petr Simek 
.RE
.PP
\fBVersion:\fP
.RS 4
V1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
26\&.03\&.2020 
.RE
.PP
\fBAttention:\fP
.RS 4
.SS "(C) COPYRIGHT PORTTRONIC"
.RE
.PP

.PP
Definition in file \fBin_js_edit_text_cpp\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
