.TH "Infrastructure" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Infrastructure \- Infrastructure layer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBConfiguration\fP"
.br
.RI "Configuration INI wrapper\&. "
.ti -1c
.RI "\fBData_plot\fP"
.br
.RI "Data plot graph\&. "
.ti -1c
.RI "\fBJerryScript\fP"
.br
.RI "JavaScript interpret\&. "
.ti -1c
.RI "\fBMain\fP"
.br
.RI "Application entry point\&. "
.ti -1c
.RI "\fBThread\fP"
.br
.RI "Thread wrapper\&. "
.ti -1c
.RI "\fBData_plot\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBredraw_event\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "vector< double > \fBv_buffer_data_plot_d\fP"
.br
.ti -1c
.RI "mpPolygon * \fBp_buffer_measure_data_polygon\fP"
.br
.ti -1c
.RI "wxString \fBdata_signal_name_str\fP"
.br
.ti -1c
.RI "wxPen \fBdata_signal_style_pen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Infrastructure layer\&. 

Library 
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
