.TH "JerryScript" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JerryScript \- JavaScript interpret\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBClass\fP"
.br
.RI "JavaScript class\&. "
.ti -1c
.RI "\fBCore\fP"
.br
.RI "JavaScript interpreter core function\&. "
.ti -1c
.RI "\fBPort\fP"
.br
.RI "JavaScript interpreter port\&. "
.ti -1c
.RI "\fBDebuger\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
JavaScript interpret\&. 

Basic JavaScript interpreter\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
