.TH "jerry_object_native_info_t" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jerry_object_native_info_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <in_jerryscript_core_h\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBjerry_object_native_free_callback_t\fP \fBfree_cb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type information of a native pointer\&. 
.PP
Definition at line 346 of file in_jerryscript_core_h\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBjerry_object_native_free_callback_t\fP free_cb"
the free callback of the native pointer 
.PP
Definition at line 348 of file in_jerryscript_core_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
