.TH "jerryscript_c" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jerryscript_c
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <in_jerryscript_port_h\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBjerryscript_c\fP (\fBuart_port\fP *p_com_uart_port, void *p_gui_main_frame_void, bool debug_b, bool init_b)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~jerryscript_c\fP (void)"
.br
.RI "Destructor\&. "
.ti -1c
.RI "uint32_t \fBrun\fP (wxString script_str)"
.br
.RI "Run script\&. "
.ti -1c
.RI "void \fBstop\fP (void)"
.br
.RI "Stop script\&. "
.ti -1c
.RI "void \fBcall_event\fP (wxString event_str, uint32_t component_id_ui32)"
.br
.RI "Call JS event function\&. "
.ti -1c
.RI "void \fBreg_class\fP (void)"
.br
.RI "Register JS class\&. "
.ti -1c
.RI "void \fBdereg_class\fP (void)"
.br
.RI "Deregister JS class\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class 
.PP
Definition at line 63 of file in_jerryscript_port_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
