.TH "jerry_property_descriptor_t" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jerry_property_descriptor_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <in_jerryscript_core_h\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBis_value_defined\fP"
.br
.ti -1c
.RI "bool \fBis_get_defined\fP"
.br
.ti -1c
.RI "bool \fBis_set_defined\fP"
.br
.ti -1c
.RI "bool \fBis_writable_defined\fP"
.br
.ti -1c
.RI "bool \fBis_writable\fP"
.br
.ti -1c
.RI "bool \fBis_enumerable_defined\fP"
.br
.ti -1c
.RI "bool \fBis_enumerable\fP"
.br
.ti -1c
.RI "bool \fBis_configurable_defined\fP"
.br
.ti -1c
.RI "bool \fBis_configurable\fP"
.br
.ti -1c
.RI "\fBjerry_value_t\fP \fBvalue\fP"
.br
.ti -1c
.RI "\fBjerry_value_t\fP \fBgetter\fP"
.br
.ti -1c
.RI "\fBjerry_value_t\fP \fBsetter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
StructDescription of ECMA property descriptor\&. 
.PP
Definition at line 191 of file in_jerryscript_core_h\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBjerry_value_t\fP getter"
[[Get]] 
.PP
Definition at line 224 of file in_jerryscript_core_h\&.h\&.
.SS "bool is_configurable"
[[Configurable]] 
.PP
Definition at line 218 of file in_jerryscript_core_h\&.h\&.
.SS "bool is_configurable_defined"
Is [[Configurable]] defined? 
.PP
Definition at line 215 of file in_jerryscript_core_h\&.h\&.
.SS "bool is_enumerable"
[[Enumerable]] 
.PP
Definition at line 212 of file in_jerryscript_core_h\&.h\&.
.SS "bool is_enumerable_defined"
Is [[Enumerable]] defined? 
.PP
Definition at line 209 of file in_jerryscript_core_h\&.h\&.
.SS "bool is_get_defined"
Is [[Get]] defined? 
.PP
Definition at line 197 of file in_jerryscript_core_h\&.h\&.
.SS "bool is_set_defined"
Is [[Set]] defined? 
.PP
Definition at line 200 of file in_jerryscript_core_h\&.h\&.
.SS "bool is_value_defined"
Is [[Value]] defined? 
.PP
Definition at line 194 of file in_jerryscript_core_h\&.h\&.
.SS "bool is_writable"
[[Writable]] 
.PP
Definition at line 206 of file in_jerryscript_core_h\&.h\&.
.SS "bool is_writable_defined"
Is [[Writable]] defined? 
.PP
Definition at line 203 of file in_jerryscript_core_h\&.h\&.
.SS "\fBjerry_value_t\fP setter"
[[Set]] 
.PP
Definition at line 227 of file in_jerryscript_core_h\&.h\&.
.SS "\fBjerry_value_t\fP value"
[[Value]] 
.PP
Definition at line 221 of file in_jerryscript_core_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
