.TH "led_buffer_t" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
led_buffer_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBsizer_index_d\fP"
.br
.ti -1c
.RI "double \fBon_color_d\fP"
.br
.ti -1c
.RI "double \fBoff_color_d\fP"
.br
.ti -1c
.RI "wxLed * \fBp_data_wxled\fP"
.br
.ti -1c
.RI "bool \fBstate_b\fP"
.br
.ti -1c
.RI "bool \fBstate_old_b\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define
.PP
Struct 
.PP
Definition at line 59 of file in_js_gui_led_cpp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
