.TH "Main" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main \- Application entry point\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBmain_app\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIMPLEMENT_APP\fP (\fBmain_app\fP)"
.br
.ti -1c
.RI "virtual bool \fBOnInit\fP ()"
.br
.RI "Windows window constructor\&. "
.in -1c
.SH "Detailed Description"
.PP 
Application entry point\&. 


.SH "Function Documentation"
.PP 
.SS "IMPLEMENT_APP (\fBmain_app\fP)"
Function 
.SS "bool OnInit ()\fC [virtual]\fP"

.PP
Windows window constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 85 of file in_main_app_cpp\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
