.TH "main_frame_js_c" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main_frame_js_c
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <in_js_class_main_frame_js_h\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreg_host_class\fP (void *p_gui_main_frame_void, wxCondition *p_data_wxcondition)"
.br
.RI "Registration object in to class\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static uint32_t \fBgui\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "GUI base function (JS function 'gui') "
.ti -1c
.RI "static uint32_t \fBconsole_rx_enable\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "GUI enable console rx data (JS method 'console_rx_enable') "
.ti -1c
.RI "static uint32_t \fBis_console_rx_enable\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "GUI enable console rx data (JS method 'is_console_rx_enable') "
.ti -1c
.RI "static uint32_t \fBjs_printf\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "GUI textctrl console printf data (JS method 'printf') "
.ti -1c
.RI "static uint32_t \fBstatus\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "GUI StatusText status bar (JS method 'status') "
.ti -1c
.RI "static uint32_t \fBclear\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "GUI textctrl console clear data (JS method 'clear') "
.ti -1c
.RI "static uint32_t \fBopen\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "GUI Open port (JS method 'open') "
.ti -1c
.RI "static uint32_t \fBclose\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "GUI close port (JS method 'close') "
.ti -1c
.RI "static uint32_t \fBget_open_status\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "GUI Get port open status (JS method 'get_open_status') "
.ti -1c
.RI "static uint32_t \fBget_data\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "GUI Get input text (JS method 'get_data') "
.ti -1c
.RI "static uint32_t \fBset_progress\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "GUI Get input text (JS method 'set_status') "
.ti -1c
.RI "static uint32_t \fBreg_event\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Set GUI send data event (JS method 'reg_event') "
.ti -1c
.RI "static uint32_t \fBhide\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Hide main frame (JS method 'hide') "
.ti -1c
.RI "static uint32_t \fBcall\fP (void *p_parametr_void)"
.br
.RI "Call Tx data send event (Must be called form JS thread) "
.in -1c
.SH "Detailed Description"
.PP 
Class 
.PP
Definition at line 53 of file in_js_class_main_frame_js_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
