.TH "packet_buffer_t" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packet_buffer_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBevent_type_ui32\fP"
.br
.ti -1c
.RI "uint32_t \fBlength_ui32\fP"
.br
.ti -1c
.RI "uint8_t \fBdata_sui8\fP [\fBd_buffer_size\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct 
.PP
Definition at line 61 of file in_js_class_uart_js_cpp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
