.TH "panel_js_c" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel_js_c
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <in_js_class_panel_js_h\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreg_host_class\fP (void *p_gui_interface_void)"
.br
.RI "Registration object in to class\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static uint32_t \fBadd\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Add new AUI panel (JS function 'now') "
.ti -1c
.RI "static uint32_t \fBset\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Set panel show (JS function 'set') "
.ti -1c
.RI "static uint32_t \fBget\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Get panel show state (JS function 'get') "
.ti -1c
.RI "static uint32_t \fBget_sizer\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Get panel main sizer (JS function 'get_sizer') "
.in -1c
.SH "Detailed Description"
.PP 
Class 
.PP
Definition at line 51 of file in_js_class_panel_js_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
