.TH "panel_buffer_t" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel_buffer_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "wxString \fBname_str\fP"
.br
.ti -1c
.RI "double \fBsizer_index_d\fP"
.br
.ti -1c
.RI "bool \fBsizer_orientation_b\fP"
.br
.ti -1c
.RI "wxPanel * \fBp_data_wxpanel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define
.PP
Struct 
.PP
Definition at line 53 of file in_js_gui_panel_cpp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
