.TH "Port" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Port \- JavaScript interpreter port\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBevent_buffer_t\fP"
.br
.ti -1c
.RI "class \fBjerryscript_c\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBjerryscript_c\fP (\fBuart_port\fP *p_com_uart_port, void *p_gui_main_frame_void, bool debug_b, bool init_b)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~jerryscript_c\fP (void)"
.br
.RI "Destructor\&. "
.ti -1c
.RI "uint32_t \fBrun\fP (wxString script_str)"
.br
.RI "Run script\&. "
.ti -1c
.RI "uint32_t \fBstop\fP (void)"
.br
.RI "Stop script\&. "
.ti -1c
.RI "void \fBcall_event\fP (wxString event_str, uint32_t component_id_ui32)"
.br
.RI "Call JS event function\&. "
.ti -1c
.RI "void \fBreg_class\fP (void)"
.br
.RI "Register JS class\&. "
.ti -1c
.RI "void \fBdereg_class\fP (void)"
.br
.RI "Deregister JS class\&. "
.ti -1c
.RI "static uint32_t \fBcall\fP (void)"
.br
.RI "Call GUI event (Must be called form JS thread) "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "double \fBg_time_d\fP"
.br
.ti -1c
.RI "double \fBg_time_ms_d\fP"
.br
.ti -1c
.RI "bool \fBl_in_js_port_gui_enable_b\fP = false"
.br
.ti -1c
.RI "vector< \fBevent_buffer_t\fP > \fBlv_main_event_buffer\fP"
.br
.ti -1c
.RI "uint32_t \fBl_exit_event_fct_ui32\fP"
.br
.ti -1c
.RI "bool \fBl_exit_event_fct_reg_b\fP = false"
.br
.ti -1c
.RI "uint32_t \fBl_exit_state_ui32\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
JavaScript interpreter port\&. 


.SH "Function Documentation"
.PP 
.SS "uint32_t call (void)\fC [static]\fP"

.PP
Call GUI event (Must be called form JS thread) 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
uint32_t : number of item in UART buffer 
.RE
.PP

.PP
Definition at line 300 of file in_jerryscript_port_cpp\&.cpp\&.
.SS "void call_event (wxString event_str, uint32_t component_id_ui32)"

.PP
Call JS event function\&. 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP event_str : Event function name 
.br
\fI[IN]\fP component_id_ui32 : GUI component buffer index 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 197 of file in_jerryscript_port_cpp\&.cpp\&.
.SS "void dereg_class (void)"

.PP
Deregister JS class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 286 of file in_jerryscript_port_cpp\&.cpp\&.
.SS "\fBjerryscript_c\fP (\fBuart_port\fP * p_com_uart_port, void * p_gui_main_frame_void, bool debug_b, bool init_b)"

.PP
Constructor\&. Function
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP p_com_uart_port : Communication port object 
.br
\fI[IN]\fP p_gui_main_frame_void : GUI frame pointer 
.br
\fI[IN]\fP debug_b : Script debug enable 
.br
\fI[IN]\fP init_b : Jerry script core initialization 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 96 of file in_jerryscript_port_cpp\&.cpp\&.
.SS "void reg_class (void)"

.PP
Register JS class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 218 of file in_jerryscript_port_cpp\&.cpp\&.
.SS "uint32_t run (wxString script_str)"

.PP
Run script\&. 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP script_str : Script text 
.RE
.PP
\fBReturns:\fP
.RS 4
uint32_t : Run status 
.RE
.PP

.PP
Definition at line 143 of file in_jerryscript_port_cpp\&.cpp\&.
.SS "uint32_t stop (void)"

.PP
Stop script\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
uint32_t : Stop state 
.RE
.PP

.PP
Definition at line 173 of file in_jerryscript_port_cpp\&.cpp\&.
.SS "~\fBjerryscript_c\fP (void)"

.PP
Destructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 126 of file in_jerryscript_port_cpp\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "double g_time_d"
Global variable 
.PP
Definition at line 65 of file in_jerryscript_port_cpp\&.cpp\&.
.SS "bool l_in_js_port_gui_enable_b = false"
Local variable 
.PP
Definition at line 74 of file in_jerryscript_port_cpp\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
