.TH "signal_buffer_t" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
signal_buffer_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "wxString \fBname_str\fP"
.br
.ti -1c
.RI "wxPen \fBsignal_style_pen\fP"
.br
.ti -1c
.RI "uint32_t \fBgraph_ui32\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 70 of file in_js_gui_graph_cpp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
