.TH "Static_text" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Static_text \- Static text class definition\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBstatic_text_js_c\fP"
.br
.ti -1c
.RI "struct \fBstatic_text_buffer_t\fP"
.br
.ti -1c
.RI "struct \fBtextctrl_buffer_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreg_host_class\fP (void *p_gui_interface_void)"
.br
.RI "Registration object in to class\&. "
.ti -1c
.RI "static uint32_t \fBadd\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Add new Static text (JS function 'add') "
.ti -1c
.RI "static uint32_t \fBset\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Set static text (JS method 'set') "
.ti -1c
.RI "uint32_t \fBadd_static_text\fP (double sizer_index_d, wxString text_str, double proportion_d, bool expand_b)"
.br
.RI "Add static_text\&. "
.ti -1c
.RI "bool \fBset_static_text\fP (double static_text_index_d, wxString text_str)"
.br
.RI "Set static_text text\&. "
.ti -1c
.RI "uint32_t \fBadd_textctrl\fP (double sizer_index_d, wxString text_str, double proportion_d, bool expand_b, bool multiline_b)"
.br
.RI "Add Text control\&. "
.ti -1c
.RI "bool \fBset_textctrl\fP (double static_text_index_d, wxString text_str)"
.br
.RI "Set textctrl text\&. "
.ti -1c
.RI "bool \fBappend_textctrl\fP (double static_text_index_d, wxString text_str)"
.br
.RI "Append textctrl text\&. "
.ti -1c
.RI "wxString \fBget_textctrl\fP (double static_text_index_d, uint32_t line_ui32)"
.br
.RI "Get textctrl text\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "vector< \fBstatic_text_buffer_t\fP > \fBlv_data_static_text_buffer\fP"
.br
.ti -1c
.RI "uint32_t \fBl_cnt_static_text_ui32\fP = 0"
.br
.ti -1c
.RI "vector< \fBtextctrl_buffer_t\fP > \fBlv_data_textctrl_buffer\fP"
.br
.ti -1c
.RI "uint32_t \fBl_cnt_textctrl_ui32\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Static text class definition\&. 

GUI static_text component\&.
.SH "Function Documentation"
.PP 
.SS "uint32_t add (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t * p_args_ui32, const uint32_t args_cnt_ui32)\fC [static]\fP"

.PP
Add new Static text (JS function 'add') 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP funct_ui32 : Unused 
.br
\fI[IN]\fP this_ui32 : Pointer on construct class 
.br
\fI[IN]\fP p_args_ui32 : Pointer on argument field 
.br
\fI[IN]\fP args_cnt_ui32 : Argument field size 
.RE
.PP
\fBReturns:\fP
.RS 4
uint32_t : returned data 
.RE
.PP

.PP
Definition at line 107 of file in_js_class_static_text_js_cpp\&.cpp\&.
.SS "uint32_t add_static_text (double sizer_index_d, wxString text_str, double proportion_d, bool expand_b)"

.PP
Add static_text\&. Function
.PP
\fBParameters:\fP
.RS 4
\fIsizer_index_d\fP : Parent sizer index 
.br
\fItext_str\fP : Text 
.br
\fIproportion_d\fP : Relative proportion item in sizer 
.br
\fIexpand_b\fP : Expand 
.RE
.PP
\fBReturns:\fP
.RS 4
uint32_t : New static_text buffer index 
.RE
.PP

.PP
Definition at line 90 of file in_js_gui_static_text_cpp\&.cpp\&.
.SS "uint32_t add_textctrl (double sizer_index_d, wxString text_str, double proportion_d, bool expand_b, bool multiline_b)"

.PP
Add Text control\&. Function
.PP
\fBParameters:\fP
.RS 4
\fIsizer_index_d\fP : Parent sizer index 
.br
\fItext_str\fP : Text 
.br
\fIproportion_d\fP : Relative proportion item in sizer 
.br
\fIexpand_b\fP : Expand 
.br
\fImultiline_b\fP : Multiline status 
.RE
.PP
\fBReturns:\fP
.RS 4
uint32_t : New textctrl buffer index 
.RE
.PP

.PP
Definition at line 96 of file in_js_gui_textctrl_cpp\&.cpp\&.
.SS "bool append_textctrl (double static_text_index_d, wxString text_str)"

.PP
Append textctrl text\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstatic_text_index_d\fP : Static text index 
.br
\fItext_str\fP : Text 
.RE
.PP
\fBReturns:\fP
.RS 4
bool : textctrl change status 
.RE
.PP

.PP
Definition at line 151 of file in_js_gui_textctrl_cpp\&.cpp\&.
.SS "wxString get_textctrl (double static_text_index_d, uint32_t line_ui32)"

.PP
Get textctrl text\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstatic_text_index_d\fP : Static text index 
.br
\fIline_ui32\fP : Read line number 
.RE
.PP
\fBReturns:\fP
.RS 4
wxString : textctrl text string 
.RE
.PP

.PP
Definition at line 176 of file in_js_gui_textctrl_cpp\&.cpp\&.
.SS "void reg_host_class (void * p_gui_interface_void)"

.PP
Registration object in to class\&. Function
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP p_gui_interface_void : Pointer on registered class 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 61 of file in_js_class_static_text_js_cpp\&.cpp\&.
.SS "uint32_t set (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t * p_args_ui32, const uint32_t args_cnt_ui32)\fC [static]\fP"

.PP
Set static text (JS method 'set') 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP funct_ui32 : Unused 
.br
\fI[IN]\fP this_ui32 : Pointer on construct class 
.br
\fI[IN]\fP p_args_ui32 : Pointer on argument field 
.br
\fI[IN]\fP args_cnt_ui32 : Argument field size 
.RE
.PP
\fBReturns:\fP
.RS 4
uint32_t : returned data 
.RE
.PP

.PP
Definition at line 161 of file in_js_class_static_text_js_cpp\&.cpp\&.
.SS "bool set_static_text (double static_text_index_d, wxString text_str)"

.PP
Set static_text text\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstatic_text_index_d\fP : Static text index 
.br
\fItext_str\fP : Text 
.RE
.PP
\fBReturns:\fP
.RS 4
bool : static_text change status 
.RE
.PP

.PP
Definition at line 115 of file in_js_gui_static_text_cpp\&.cpp\&.
.SS "bool set_textctrl (double static_text_index_d, wxString text_str)"

.PP
Set textctrl text\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstatic_text_index_d\fP : Static text index 
.br
\fItext_str\fP : Text 
.RE
.PP
\fBReturns:\fP
.RS 4
bool : textctrl change status 
.RE
.PP

.PP
Definition at line 126 of file in_js_gui_textctrl_cpp\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "vector<\fBstatic_text_buffer_t\fP> lv_data_static_text_buffer"
Local variable 
.PP
Definition at line 71 of file in_js_gui_static_text_cpp\&.cpp\&.
.SS "vector<\fBtextctrl_buffer_t\fP> lv_data_textctrl_buffer"
Local variable 
.PP
Definition at line 76 of file in_js_gui_textctrl_cpp\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
