.TH "timer_buffer_t" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timer_buffer_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBevent_fct_ui32\fP"
.br
.ti -1c
.RI "double \fBcnt_d\fP"
.br
.ti -1c
.RI "double \fBperiod_d\fP"
.br
.ti -1c
.RI "bool \fBrun_b\fP"
.br
.ti -1c
.RI "bool \fBone_shot_b\fP"
.br
.ti -1c
.RI "bool \fBone_flag_b\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct 
.PP
Definition at line 53 of file in_js_class_timer_js_cpp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
