.TH "uart_event_buffer_t" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uart_event_buffer_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuart_event_fct\fP \fBp_usr_uart_event_fct\fP"
.br
.ti -1c
.RI "void * \fBp_parametr_void\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 114 of file hw_dr_uart_driver_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
