.TH "UART_terminal" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_terminal \- UART terminal monitor\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBmain_frame\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBd_ap_uart_terminal_tx_buffer_length\fP   4096"
.br
.ti -1c
.RI "#define \fBd_ap_uart_terminal_status_port\fP   0"
.br
.ti -1c
.RI "#define \fBd_ap_uart_terminal_status_script\fP   1"
.br
.ti -1c
.RI "#define \fBd_ap_uart_terminal_info_script\fP   2"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBsend_event_fct\fP) (void *p_parametr_void, uint8_t *p_data_sui8, uint32_t length_ui32)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain_frame\fP (wxWindow *p_parent_window, wxArrayString *p_cmd_arg_arraystring)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~main_frame\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "void \fBgui\fP (bool status_b)"
.br
.RI "Set frame show status\&. "
.ti -1c
.RI "\fBconfig_ini\fP * \fBget_project\fP (void)"
.br
.RI "Get project configuration object\&. "
.ti -1c
.RI "void \fBconsole_rx_enable\fP (bool status_b)"
.br
.RI "Set RX data show status\&. "
.ti -1c
.RI "bool \fBis_console_rx_enable\fP (void)"
.br
.RI "Get RX console show status\&. "
.ti -1c
.RI "void \fBprintf\fP (wxString console_text_str)"
.br
.RI "Print string on console\&. "
.ti -1c
.RI "void \fBstatus\fP (wxString status_text_str)"
.br
.RI "Print string on status bar\&. "
.ti -1c
.RI "void \fBclear\fP (void)"
.br
.RI "Clear console text\&. "
.ti -1c
.RI "void \fBopen_port\fP (void)"
.br
.RI "Open UART with GUI setting\&. "
.ti -1c
.RI "void \fBclose_port\fP (void)"
.br
.RI "Close port wit GUI setting\&. "
.ti -1c
.RI "uart_status_t \fBget_open_status\fP (void)"
.br
.RI "Get port open status\&. "
.ti -1c
.RI "void \fBset_config\fP (\fBuart_cfg_t\fP data_uart_cfg)"
.br
.RI "Set UART port settings in GUI\&. "
.ti -1c
.RI "\fBuart_cfg_t\fP \fBget_config\fP (void)"
.br
.RI "Get UART port settings from GUI\&. "
.ti -1c
.RI "wxString \fBget_data\fP (wxString text_str)"
.br
.RI "Get data from input dialog\&. "
.ti -1c
.RI "void \fBset_progress\fP (wxString text_str, uint32_t progress_ui32)"
.br
.RI "Set progress dialog\&. "
.ti -1c
.RI "void \fBset_send_event\fP (\fBsend_event_fct\fP data_send_event_fct, void *p_parametr_void)"
.br
.RI "Set external event after send button click\&. "
.ti -1c
.RI "uint32_t \fBrun_script\fP (wxString path_str)"
.br
.RI "Run JS script\&. "
.ti -1c
.RI "void \fBstop_script\fP (void)"
.br
.RI "Stop JS script\&. "
.ti -1c
.RI "static void \fBstop_event\fP (void)"
.br
.RI "Stop JS script event\&. "
.in -1c
.SH "Detailed Description"
.PP 
UART terminal monitor\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define d_ap_uart_terminal_tx_buffer_length   4096"
Define 
.PP
Definition at line 50 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* send_event_fct) (void *p_parametr_void, uint8_t *p_data_sui8, uint32_t length_ui32)"
Type 
.PP
Definition at line 62 of file ap_uart_terminal_frame_h\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void clear (void)"

.PP
Clear console text\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 579 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "void close_port (void)"

.PP
Close port wit GUI setting\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 683 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "void console_rx_enable (bool status_b)"

.PP
Set RX data show status\&. 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP status_b : Show RX data status 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 527 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "\fBuart_cfg_t\fP get_config (void)"

.PP
Get UART port settings from GUI\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
data_uart_cfg : UART port configuration structure 
.RE
.PP

.PP
Definition at line 773 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "wxString get_data (wxString text_str)"

.PP
Get data from input dialog\&. 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP text_str : Dialog text 
.RE
.PP
\fBReturns:\fP
.RS 4
wxString : Input text 
.RE
.PP

.PP
Definition at line 812 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "uart_status_t get_open_status (void)"

.PP
Get port open status\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
uart_status_t : UART port status 
.RE
.PP

.PP
Definition at line 721 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "\fBconfig_ini\fP * get_project (void)"

.PP
Get project configuration object\&. 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP status_b : Show GUI frame 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 515 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "void gui (bool status_b)"

.PP
Set frame show status\&. 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP status_b : Show GUI frame 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 500 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "bool is_console_rx_enable (void)"

.PP
Get RX console show status\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool : Actual console enable status 
.RE
.PP

.PP
Definition at line 540 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "\fBmain_frame\fP (wxWindow * parent, wxArrayString * p_cmd_arg_arraystring)"

.PP
Constructor\&. Function
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP parent : Pointer on window generated by OS for application 
.br
\fI[IN]\fP id : Window identification 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 127 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "void open_port (void)"

.PP
Open UART with GUI setting\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 592 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "void printf (wxString console_text_str)"

.PP
Print string on console\&. 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP console_text_str : Print text 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 552 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "uint32_t run_script (wxString path_str)"

.PP
Run JS script\&. 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP path_str : Script path 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 865 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "void set_config (\fBuart_cfg_t\fP data_uart_cfg)"

.PP
Set UART port settings in GUI\&. 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP data_uart_cfg : UART port configuration structure 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 733 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "void set_progress (wxString text_str, uint32_t progress_ui32)"

.PP
Set progress dialog\&. 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP text_str : Dialog text 
.br
\fI[IN]\fP progress_ui32 : Progress 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 832 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "void set_send_event (\fBsend_event_fct\fP data_send_event_fct, void * p_parametr_void)"

.PP
Set external event after send button click\&. 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP data_send_event_fct : Event function pointer 
.br
\fI[IN]\fP p_parametr_void : Event function parameter 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 851 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "void status (wxString status_text_str)"

.PP
Print string on status bar\&. 
.PP
\fBParameters:\fP
.RS 4
\fI[IN]\fP console_text_str : Print text 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 566 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "void stop_event (void)\fC [static]\fP"

.PP
Stop JS script event\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 939 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "void stop_script (void)"

.PP
Stop JS script\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 917 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SS "~\fBmain_frame\fP ()\fC [virtual]\fP"

.PP
Destructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 432 of file ap_uart_terminal_frame_cpp\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
