.TH "uart_js_c" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uart_js_c
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <in_js_class_uart_js_h\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreg_host_class\fP (\fBuart_port\fP *p_com_uart_port, wxCondition *p_data_wxcondition)"
.br
.RI "Registration object in to class\&. "
.ti -1c
.RI "void \fBdereg_host_class\fP (void)"
.br
.RI "Deregistration object in to class\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static uint32_t \fBopen\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Open UART port (JS method 'open') "
.ti -1c
.RI "static uint32_t \fBclose\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Close UART port (JS method 'close') "
.ti -1c
.RI "static uint32_t \fBreg_event\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Set Rx event (JS method 'reg_event') "
.ti -1c
.RI "static uint32_t \fBwrite\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Write UART (JS method 'write') "
.ti -1c
.RI "static uint32_t \fBget_ctrl\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Get UART control line status (JS method 'get_ctrl') "
.ti -1c
.RI "static uint32_t \fBset_ctrl\fP (const uint32_t funct_ui32, const uint32_t this_ui32, const uint32_t *p_args_ui32, const uint32_t args_cnt_ui32)"
.br
.RI "Set UART control line status (JS method 'set_ctrl') "
.ti -1c
.RI "static uint32_t \fBcall\fP (void *p_parametr_void)"
.br
.RI "Call UART data RX event (Must be called form JS thread) "
.in -1c
.SH "Detailed Description"
.PP 
Class 
.PP
Definition at line 53 of file in_js_class_uart_js_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
