.TH "var_t" 3 "Mon Apr 20 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
var_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "wxString \fBtype_str\fP"
.br
.ti -1c
.RI "wxString \fBname_str\fP"
.br
.ti -1c
.RI "bool \fBclass_b\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file in_js_edit_text_autocomp_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
