.TH "Application" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application \- Application layer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBGUI\fP"
.br
.RI "GUI window\&. "
.ti -1c
.RI "\fBUART_terminal\fP"
.br
.RI "UART terminal monitor\&. "
.in -1c
.SH "Detailed Description"
.PP 
Application layer\&. 

Library 
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
