.TH "data_plot_buffer" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_plot_buffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <in_data_plot_graph_h\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< double > \fBv_buffer_data_plot_d\fP"
.br
.ti -1c
.RI "mpPolygon * \fBp_buffer_measure_data_polygon\fP"
.br
.ti -1c
.RI "wxString \fBdata_signal_name_str\fP"
.br
.ti -1c
.RI "wxPen \fBdata_signal_style_pen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct 
.PP
Definition at line 51 of file in_data_plot_graph_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
