.TH "data_plot" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_plot
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <in_data_plot_graph_h\&.h>\fP
.PP
Inherits wxPanel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdata_plot\fP (wxWindow *p_parent_wxwindow, wxString graph_label_str, double draph_range_d, double buffer_length_d, double time_step_d)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~data_plot\fP (void)"
.br
.RI "Destructor\&. "
.ti -1c
.RI "void \fBinsert_signal\fP (wxString signal_label_str, wxPen signal_style_pen)"
.br
.RI "Insert signal in to graph\&. "
.ti -1c
.RI "uint32_t \fBget_signal\fP (void)"
.br
.RI "Get number of signal in graph\&. "
.ti -1c
.RI "uint8_t \fBinsert_data\fP (uint32_t index_ui32, double data_d)"
.br
.RI "Insert data in to specific signal buffer\&. "
.ti -1c
.RI "void \fBtime_increment\fP (void)"
.br
.RI "Increment time X scale (call after insert all single data) "
.ti -1c
.RI "void \fBredraw_event\fP (void)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const long \fBl_id_graph_name_wxstatictext\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBl_id_x_axis_mpscalex\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBl_id_y_axis_mpscalex\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBl_id_graph_mpwindow\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBl_id_graph_signal_wxgrid\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBl_id_redraw_wxtimer\fP = wxNewId()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class 
.PP
Definition at line 65 of file in_data_plot_graph_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
