.TH "D:/project/uart_terminal/hardware/drivers/uart/hw_dr_uart_driver_h.h" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/project/uart_terminal/hardware/drivers/uart/hw_dr_uart_driver_h.h \- Driver for UART communication\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <windows\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBuart_cfg_t\fP"
.br
.ti -1c
.RI "struct \fBuart_event_buffer_t\fP"
.br
.ti -1c
.RI "class \fBuart_port\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDLL_EXPORT\fP   __declspec(dllimport)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBuart_event_fct\fP) (void *p_parametr_void, uint32_t event_type_ui32, uint8_t *p_data_sui8, uint32_t length_ui32)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBuart_com_ctrl_in_t\fP { \fBe_rx\fP = 1, \fBe_cts\fP = 2, \fBe_dsr\fP = 3, \fBe_ring\fP = 4, \fBe_rlsd\fP = 5 }"
.br
.ti -1c
.RI "enum \fBuart_com_ctrl_out_t\fP { \fBe_dtr\fP = 0, \fBe_rts\fP = 1, \fBe_break\fP = 2, \fBe_xoff\fP = 3, \fBe_xon\fP = 4 }"
.br
.ti -1c
.RI "enum \fBuart_status_t\fP { \fBe_00_open_error\fP = 0, \fBe_01_open\fP = 1, \fBe_02_handle_error\fP = 2, \fBe_03_write_configuration_error\fP = 3, \fBe_04_write_timeout_error\fP = 4, \fBe_05_close_error\fP = 5, \fBe_06_close\fP = 6, \fBe_07_opened\fP = 7 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Driver for UART communication\&. 


.PP
\fBAuthor:\fP
.RS 4
Ing\&. Petr Simek 
.RE
.PP
\fBVersion:\fP
.RS 4
V2\&.2 
.RE
.PP
\fBDate:\fP
.RS 4
29\&.04\&.2015 
.RE
.PP
\fBAttention:\fP
.RS 4
.SS "(C) COPYRIGHT PORTTRONIC"
.RE
.PP

.PP
Definition in file \fBhw_dr_uart_driver_h\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
