.TH "D:/project/uart_terminal/infrastructure/jerryscript/gui/in_js_gui_frame_cpp.cpp" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/project/uart_terminal/infrastructure/jerryscript/gui/in_js_gui_frame_cpp.cpp \- GUI window component creator\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'in_js_gui_frame_h\&.h'\fP
.br
\fC#include 'in_jerryscript_port_h\&.h'\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include <wx/string\&.h>\fP
.br
\fC#include 'ap_uart_terminal_frame_h\&.h'\fP
.br
\fC#include 'icon/lp_in_js_gui_ico_xpm\&.xpm'\fP
.br
\fC#include <wx/imaglist\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBl_frmae_show_b\fP = false"
.br
.ti -1c
.RI "bool \fBl_frame_show_bkp_b\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
GUI window component creator\&. 


.PP
\fBAuthor:\fP
.RS 4
Ing\&. Petr Simek 
.RE
.PP
\fBVersion:\fP
.RS 4
V1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
17\&.07\&.2018 
.RE
.PP
\fBAttention:\fP
.RS 4
.SS "(C) COPYRIGHT PORTTRONIC"
.RE
.PP

.PP
Definition in file \fBin_js_gui_frame_cpp\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
