.TH "jerry_heap_stats_t" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jerry_heap_stats_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <in_jerryscript_core_h\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBversion\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBallocated_bytes\fP"
.br
.ti -1c
.RI "size_t \fBpeak_allocated_bytes\fP"
.br
.ti -1c
.RI "size_t \fBreserved\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description of JerryScript heap memory stats\&. It is for memory profiling\&. 
.PP
Definition at line 234 of file in_jerryscript_core_h\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "size_t jerry_heap_stats_t::allocated_bytes"
currently allocated bytes 
.PP
Definition at line 238 of file in_jerryscript_core_h\&.h\&.
.SS "size_t jerry_heap_stats_t::peak_allocated_bytes"
peak allocated bytes 
.PP
Definition at line 239 of file in_jerryscript_core_h\&.h\&.
.SS "size_t jerry_heap_stats_t::reserved[4]"
padding for future extensions 
.PP
Definition at line 240 of file in_jerryscript_core_h\&.h\&.
.SS "size_t jerry_heap_stats_t::size"
heap total size 
.PP
Definition at line 237 of file in_jerryscript_core_h\&.h\&.
.SS "size_t jerry_heap_stats_t::version"
the version of the stats struct 
.PP
Definition at line 236 of file in_jerryscript_core_h\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
