.TH "textctrl_buffer_t" 3 "Sun Feb 16 2020" "Version V2.0" "UART Terminal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textctrl_buffer_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBsizer_index_d\fP"
.br
.ti -1c
.RI "wxString \fBtext_str\fP"
.br
.ti -1c
.RI "double \fBproportion_d\fP"
.br
.ti -1c
.RI "double \fBexpand_b\fP"
.br
.ti -1c
.RI "bool \fBmultiline_b\fP"
.br
.ti -1c
.RI "bool \fBupdate_b\fP"
.br
.ti -1c
.RI "bool \fBappend_b\fP"
.br
.ti -1c
.RI "bool \fBread_b\fP"
.br
.ti -1c
.RI "uint32_t \fBread_line_ui32\fP"
.br
.ti -1c
.RI "wxString \fBread_text_str\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBp_data_wxtextctrl\fP"
.br
.ti -1c
.RI "int32_t \fBobject_id_i32\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define
.PP
Struct 
.PP
Definition at line 54 of file in_js_gui_textctrl_cpp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UART Terminal from the source code\&.
